### ISSUE TITLE
Deleting a message after processing it causes other plugins to crash

### ISSUE THREAD

**Issue by gradiuscypher** [gradiuscypher/discord_gradiusbot#12]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/gradius/code/discord_gradiusbot/public_plugins/help.py", line 23, in action
    if split_content[0] == "!help":
IndexError: list index out of range
```

**Comment by gradiuscypher** [comment]
I believe this is fixed with the most recent commit.

**Comment by gradiuscypher** [comment]
This is not fixed. Messages still get deleted before they make their way through all of the plugins.
