### ISSUE TITLE
members returning None after message was sent via PM, also other Exceptions during message

### ISSUE THREAD

**Issue by gradiuscypher** [gradiuscypher/discord_gradiusbot#20]
```
future: <Task finished coro=<action() done, defined at /home/gradius/code/discord_gradiusbot/private_plugins/ss_optional_groups.py:12> exception=AttributeError("'NoneType' object has no attribute 'roles'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/gradius/code/discord_gradiusbot/private_plugins/ss_optional_groups.py", line 34, in action
    yield from client.add_roles(target_user, optional_groups[split_content[1].lower()])
  File "/home/gradius/code/discord_gradiusbot/venv3/lib/python3.4/site-packages/discord/client.py", line 2112, in add_roles
    new_roles = utils._unique(role.id for role in itertools.chain(member.roles, roles))
AttributeError: 'NoneType' object has no attribute 'roles'
Task exception was never retrieved

future: <Task finished coro=<action() done, defined at /home/gradius/code/discord_gradiusbot/private_plugins/ss_namecolor.py:13> exception=AttributeError("'NoneType' object has no attribute 'roles'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/gradius/code/discord_gradiusbot/private_plugins/ss_namecolor.py", line 35, in action
    for role in target_user.roles:
AttributeError: 'NoneType' object has no attribute 'roles'
Task exception was never retrieved
```

```
future: <Task finished coro=<action() done, defined at /home/gradius/code/discord_gradiusbot/private_plugins/ss_optional_groups.py:12> exception=AttributeError("'NoneType' object has no attribute 'roles'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/gradius/code/discord_gradiusbot/private_plugins/ss_optional_groups.py", line 47, in action
    for role in target_user.roles:
AttributeError: 'NoneType' object has no attribute 'roles'
Task exception was never retrieved
```

```
future: <Task finished coro=<action() done, defined at /home/gradius/code/discord_gradiusbot/private_plugins/ss_optional_groups.py:12> exception=AttributeError("'NoneType' object has no attribute 'roles'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/gradius/code/discord_gradiusbot/private_plugins/ss_optional_groups.py", line 60, in action
    for r in target_user.roles:
AttributeError: 'NoneType' object has no attribute 'roles'
Task exception was never retrieved
```

**Comment by gradiuscypher** [comment]
```
Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
Task exception was never retrieved
future: <Task finished coro=<action() done, defined at /home/gradius/code/discord_gradiusbot/private_plugins/ss_optional_groups.py:12> exception=ValueError('Expecting value: line 1 column 1 (char 0)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 236, in _step
    result = coro.send(value)
  File "/home/gradius/code/discord_gradiusbot/private_plugins/ss_optional_groups.py", line 34, in action
    yield from client.add_roles(target_user, optional_groups[split_content[1].lower()])
  File "/home/gradius/code/discord_gradiusbot/venv3/lib/python3.4/site-packages/discord/client.py", line 2113, in add_roles
    yield from self._replace_roles(member, new_roles)
  File "/home/gradius/code/discord_gradiusbot/venv3/lib/python3.4/site-packages/discord/client.py", line 2083, in _replace_roles
    yield from utils._verify_successful_response(r)
  File "/home/gradius/code/discord_gradiusbot/venv3/lib/python3.4/site-packages/discord/utils.py", line 175, in _verify_successful_response
    data = yield from response.json()
  File "/home/gradius/code/discord_gradiusbot/venv3/lib/python3.4/site-packages/aiohttp/client_reqrep.py", line 756, in json
    return loads(stripped.decode(encoding))
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```
