### ISSUE TITLE
Tim: Crash + Lockup - AttributeError

### ISSUE THREAD

**Issue by gradiuscypher** [gradiuscypher/discord_gradiusbot#76]
```
Jun 15 22:38:01 bots1 start_tim.sh[25386]: AttributeError: 'NoneType' object has no attribute 'id'
Jun 15 22:38:01 bots1 start_tim.sh[25386]: 2018-06-15 22:38:01,562 - banpool_manager - ERROR - Traceback (most recent call last):
Jun 15 22:38:01 bots1 start_tim.sh[25386]:   File "/home/gradius/git/discord_gradiusbot/scheduled_tasks/banpool_tasks/banpool_tasks.py", line 53, in action
Jun 15 22:38:01 bots1 start_tim.sh[25386]:     bot_perms = admin_chan.permissions_for(guild.me)
Jun 15 22:38:01 bots1 start_tim.sh[25386]:   File "/home/gradius/git/discord_gradiusbot/venv3/lib/python3.6/site-packages/discord/channel.py", line 108, in permissions_for
Jun 15 22:38:01 bots1 start_tim.sh[25386]:     base = super().permissions_for(member)
Jun 15 22:38:01 bots1 start_tim.sh[25386]:   File "/home/gradius/git/discord_gradiusbot/venv3/lib/python3.6/site-packages/discord/abc.py", line 410, in permissions_for
Jun 15 22:38:01 bots1 start_tim.sh[25386]:     if o is not None and member.id == o.id:
Jun 15 22:38:01 bots1 start_tim.sh[25386]: AttributeError: 'NoneType' object has no attribute 'id'
```

At some point in time, Tim will lock up and be unable to execute commands or perform any actions. This also has the negative side effect of spamming the logs with thousands of these entries.

Crash logs reference [this line of code](https://github.com/gradiuscypher/discord_gradiusbot/blob/master/scheduled_tasks/banpool_tasks/banpool_tasks.py#L53):
```py
                # Iterate through each server, looking for banned user IDs
                for guild in client.guilds:
                    # Validate bot's permissions
                    bot_perms = admin_chan.permissions_for(guild.me)

                    if not bot_perms.ban_members:
                        logger.error("The bot does not have ban permissions on {}[{}]".format(guild.name, guild.id))

                    else:
                        for user_id in banned_user_ids:
                            user = guild.get_member(user_id)
```

Which uses [Channel.permissions_for](http://discordpy.readthedocs.io/en/latest/api.html#discord.Channel.permissions_for) `discord.py` method.

The next line then checks to see if `bot_perms` is none, and the following `discord.py` code checks to make sure the object it's referencing is not `None`. 

I'm thinking this error may trigger during a disconnect/reconnect cycle where the bot cannot find the `admin_chan` referenced. This may be because the `admin_chan` is not reconfigured after a reconnect. Catching if `admin_chan` is none will likely prevent the loop, but won't fix the underlying problem of an undefined admin channel.

**Comment by gradiuscypher** [comment]
Updated code to most recent version of Discord.py, will validate if that helps.
